name: Build and Pack

on:
  push:
    branches:
      - master
      - develop
    tags:
      - v*
    paths:
      - .github/workflows/build.yaml
      - global.json
      - nuget.config
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - GitVersion.yaml
      - Shimakaze.MinimalApi.Plus.slnx
      - 'src/**/*'
  pull_request:
    branches:
      - master
      - develop
    paths:
      - .github/workflows/build.yaml
      - global.json
      - nuget.config
      - Directory.Build.props
      - Directory.Build.targets
      - Directory.Packages.props
      - GitVersion.yaml
      - Shimakaze.MinimalApi.Plus.slnx
      - 'src/**/*'

jobs:
  build:
    name: 构建
    runs-on: windows-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          lfs: true
          fetch-depth: 0

      - name: 配置 .Net 环境
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: 还原
        run: dotnet restore --graph --artifacts-path artifacts --locked-mode

      - name: 生成
        run: dotnet build --graph --artifacts-path artifacts --configuration Release --no-restore

      - name: 打包
        shell: pwsh
        run: |-
          Get-ChildItem src -Directory | ForEach-Object {
            dotnet pack $PSItem --graph --artifacts-path artifacts --configuration Release --no-restore --no-build --include-symbols
          }

      - name: 收集 Nuget 包
        uses: actions/upload-artifact@v6
        with:
          name: nuget-packages
          path: |
            artifacts/package/release/*
          retention-days: 3

  publish:
    needs: build
    name: 发布
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: 签出仓库
        uses: actions/checkout@v6
        with:
          sparse-checkout: ''

      - name: 配置 .Net 环境
        uses: actions/setup-dotnet@v5
        with:
          cache: false

      - name: Download a Build Artifact
        uses: actions/download-artifact@v7
        with:
          name: nuget-packages
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*

      - name: 推送 Nuget 包
        shell: pwsh
        continue-on-error: true
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          Set-Location artifacts
          dotnet nuget push *.nupkg -s nuget -k $env:NUGET_TOKEN --skip-duplicate
          Set-Location ..
